### ISSUE TITLE
location of pre-built binaries of `gr1c`

### ISSUE THREAD

**Issue by johnyf** [tulip-control/gr1c#37]
[Bintray](https://bintray.com) [shut down on May 1st, 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). The CI setup script of `tulip` [raised](https://travis-ci.org/github/tulip-control/tulip-control/jobs/772690567#L2031) an error about the SHA-256 hash.

I updated `tulip`'s CI configuration file to download `gr1c` from the GitHub release assets, as described in https://github.com/tulip-control/tulip-control/issues/246.

I am not sure whether downloading `gr1c` from elsewhere than GitHub release assets would be decided (latest change to the download was in `tulip` commit https://github.com/tulip-control/tulip-control/commit/89d77518d55a2b82136948a6dc6058226ec904af and also relevant is `tulip` commit https://github.com/tulip-control/tulip-control/commit/667499b2770aa7a58906a4e0fa1363b30e0a1ead).

Assuming that `gr1c` will be downloaded from GitHub, a relevant change seems to be to the file:

https://github.com/tulip-control/gr1c/blob/200b70e7c0c7d47a1892d3b88cafe059ec865029/doc/api_intro.md#:~:text=bintray

(The linking syntax that I used is from the ["Text Fragments"](https://wicg.github.io/scroll-to-text-fragment/#syntax) draft, because currently GitHub does not support linking to a specific line of a Markdown file.)

**Comment by slivingston** [comment]
@johnyf thanks for this careful review. I was not aware that Bintray shut down. I propose that we can put gr1c release files as assets on GitHub releases (e.g., [as on v0.13.0](https://github.com/tulip-control/gr1c/releases/tag/v0.13.0)). Actually I created #35 to automate this process.

I will update api_intro.md as you comment, and then I will close this issue.

**Comment by slivingston** [comment]
For posterity, hosting release files outside GitHub was motivated because
1. depending on GitHub for source code and release file hosting results in a single point of failure for downloading gr1c;
2. [years ago GitHub had support for release assets but removed it](https://github.blog/2012-12-12-goodbye-uploads/), and later [introduced another way to upload release assets](https://github.blog/2013-07-02-release-your-software/); because of these changes, it was not clear to me that GitHub would keep "releases" as a feature indefinitely.

Today, only the first motivation above is significant. However I do not think the current benefit of redundancy justifies the cost of hosting releases with a separate provider.

**Comment by johnyf** [comment]
@slivingston thank you for updating the documentation, and noting the motivation.

**Comment by johnyf** [comment]
Above (https://github.com/tulip-control/gr1c/issues/37#issue-910236561), I commented that GitHub does not support linking to specific lines in Markdown files. This has now changed: [GitHub supports links to Markdown files](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet#linking-to-markdown). For example, the link from above would be:

https://github.com/tulip-control/gr1c/blob/200b70e7c0c7d47a1892d3b88cafe059ec865029/doc/api_intro.md?plain=1#L14
